name: erp
description: Projeto de gestão financeira versão mobile, desenvolvido em Flutter

version: 1.9.5+10903

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  flutter_map_marker_cluster: ^0.2.8
  flutter_launcher_icons: ^0.7.5
  liquid_pull_to_refresh: ^2.0.0
  titled_navigation_bar: ^3.6.0
  rx_shared_preferences: ^1.3.1
  connectivity_wrapper: ^1.0.4
  shared_preferences: ^0.5.12
  infinite_listview: ^1.0.1+1
  responsive_widgets: ^0.1.10
  flutter_masked_text: 0.8.0
  flutter_screenutil: ^0.7.0
  simple_animations: ^2.2.2
  cupertino_icons: ^0.1.2
  device_preview: ^0.4.8
  path_provider: ^1.6.14
  connectivity: ^0.4.9
  bloc_pattern: ^2.3.2
  flutter_map: ^0.9.0
  fl_chart: ^0.9.4
  shimmer: ^1.1.1
  rxdart: ^0.24.1
  flutter_slidable: ^0.5.7
  cron: ^0.2.3
  uuid: 2.1.0
  dio: ^3.0.10
  onesignal_flutter: ^2.6.1
  intl: ^0.16.0
  http: ^0.12.2
  latlong: ^0.6.1
  sqflite: ^1.3.1
  firebase: ^7.3.0
  quick_log: ^0.4.1
  search_cep: ^1.0.4
  credit_card: ^0.1.8
  geolocator: ^5.3.2+2
  map_launcher: ^0.9.0
  flutter_launch: ^0.2.0
  sliding_up_panel: ^1.0.2
  flutter_spinkit: "^4.1.2"
  font_awesome_flutter: ^8.9.0
  flutter_signature_pad: ^2.0.2
  argon_buttons_flutter: ^1.0.6
  credit_card_type_detector: ^1.1.0
  open_file: ^3.0.1
  share_extend: ^1.1.9
  device_info: ^0.4.2+4
  image_picker: ^0.6.7+1
  percent_indicator: ^2.1.7+1
  month_picker_dialog: ^0.3.2
  provider: ^4.3.2+2
  sqfentity: ^1.4.0+1
  sqfentity_gen: ^1.4.0
  flutter_datetime_picker: ^1.2.8

dev_dependencies:
  build_runner: ^1.10.1
  build_verify: ^1.1.1
  sqflite_common_ffi: ^1.1.0+1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - data/paises.json

    - images/logo/logo.png
    - images/logo/logofullcontrol.png

    - images/logo/atmos/iconeatmos.png
    - images/logo/atmos/iconeatmossplash.png
    - images/logo/atmos/marcaatmostemadark.png
    - images/logo/atmos/marcaatmostemalight.png
    - images/logo/fullcontrol/marcafullcontroltemalight.png
    - images/logo/fullcontrol/marcafullcontroltemadark.png
    - images/logo/fullcontrol/iconefullcontrolsplash.png
    - images/logo/fullcontrol/iconefullcontrol.png
    - images/default/user-silhouette.png
    - images/app/pay1-green.png
    - images/app/conversation.png
    - images/app/calendar_blue.png
    - images/app/correct-symbol-WHITE.png
    - images/app/pay2-red.png
    - images/app/seminformacao.png
    - images/app/appointment.png
    - images/app/vendas-gray.png
    - images/app/percentage.png
    - images/app/analytics.png
    - images/app/organize.png
    - images/app/product.png
    - images/app/empty.png
    - images/app/pin.png
    - images/app/add.png
    - images/app/edit-white.png
    - images/app/delete-white.png
    - images/app/icon-waze.png
    - images/app/icon-google-maps.png
    - images/app/money.png
    - images/arrow-left-white.png
    - images/flags/

    - images/credit_cards/icons/chip.png
    - images/credit_cards/icons/visa.png
    - images/credit_cards/icons/master.png
    - images/credit_cards/icons/maestro.png
    - images/credit_cards/icons/diners.png
    - images/credit_cards/icons/discover.png
    - images/credit_cards/icons/amex.png
    - images/credit_cards/icons/elo.png
    - images/credit_cards/icons/hiper.png
    - images/credit_cards/icons/hipercard.png
    - images/credit_cards/icons/jcb.png
    - images/credit_cards/icons/aura.png
    - images/credit_cards/icons/mir.png
    - images/credit_cards/icons/unionpay.png

    - locale/br.json
    - locale/en.json
    - locale/es.json
    - locale/de.json

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Lato-Heavy.ttf
          weight: 800
        - asset: fonts/Lato-HeavyItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Lato-Semibold.ttf
          weight: 600
        - asset: fonts/Lato-SemiboldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Lato-Medium.ttf
          weight: 500
        - asset: fonts/Lato-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Lato-Thin.ttf
          weight: 200
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Lato-Hairline.ttf
          weight: 100
        - asset: fonts/Lato-HairlineItalic.ttf
          weight: 100
          style: italic

